# Gauss Elimination

In [15]:
import numpy as np

A = np.array([[2,7,-1,3,1],
              [2,3,4,1,7],
              [6,2,-3,2,-1],
              [2,1,2,-1,2],
              [3,4,1,-2,1]],float)
B = np.array([[5],
              [7],
              [2],
              [3],
              [4]],float)
n=len(B)
X = np.zeros(n, float)

#Elimination 
for k in range(n-1):
    for i in range(k+1, n):
        factr = A[k,k]/A[i,k]
        for j in range (k,n):
            A[i,j]=A[k,j]-factr*A[i,j]
        B[i] = B[k]-factr*B[i]

#Backward substitution 

X[n-1] = B[n-1]/A[n-1,n-1]

for i in range (n-2,-1,-1):
    Sum =0
    for j in range (i+1, n):
        Sum+=A[i,j]*X[j]
    X[i] = (B[i]-Sum)/A[i,i]

Y = np.linalg.solve(A,B)
print(X)
print(Y)


[0.44444444 0.55555556 0.66666667 0.22222222 0.22222222]
[[0.44444444]
 [0.55555556]
 [0.66666667]
 [0.22222222]
 [0.22222222]]


C:\Users\User\AppData\Local\Temp\ipykernel_13140\1041719608.py:26: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  X[n-1] = B[n-1]/A[n-1,n-1]
C:\Users\User\AppData\Local\Temp\ipykernel_13140\1041719608.py:32: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  X[i] = (B[i]-Sum)/A[i,i]


# Jacobi's Method

In [16]:
import numpy as np

A = np.array([[4,1,2,-1],
              [3,6,-1,2],
              [2,-1,5,-3],
              [4,1,-3,-8]],float)
B = np.array([2,-1,3,2],float)
(n,) = np.shape(B)
X_new = np.empty(n, float)
X = np.full(n,1.0, float)
max_iter = 100
tolerance = 1*np.exp(-8)
for iteration in range (max_iter):

    for i in range (n):
        Sum = 0
        for j in range (n):
            if j!=i:
                Sum+=A[i,j]*X[j]
        X_new[i] = - (Sum-B[i])/(A[i,i])
    if (np.abs(X_new-X)<tolerance).all():
        break
    else:
        X = np.copy(X_new)

print(X)
print(iteration)

[ 0.3645813  -0.23346818  0.28505651 -0.20379138]
17


# Gauss Seidel's Method

In [21]:
import numpy as np

A = np.array([[4,1,2,-1],
              [3,6,-1,2],
              [2,-1,5,-3],
              [4,1,-3,-8]],float)
B = np.array([2,-1,3,2],float)
(n,) = np.shape(B)
X_new = np.empty(n, float)
X = np.full(n,1.0, float)
max_iter = 100
tolerance = 1*np.exp(-8)
for iteration in range (max_iter):

    for i in range (n):
        Sum = 0
        for j in range (n):
            if j!=i:
                Sum+=A[i,j]*X_new[j]  #The difference between Jacobi and Gauss Seidel
        X_new[i] = - (Sum-B[i])/(A[i,i])
    if (np.abs(X_new-X)<tolerance).all():
        break
    else:
        X = np.copy(X_new)

print(X)
print(iteration)

[ 0.36550004 -0.23424488  0.28500187 -0.20340629]
8


For applying Gauss Seidel and Jacobi Method diagonal dominance is important. For this reason the first problem doesn't run successfully. 

# Gauss Jordan Method

In [32]:
import numpy as np

A = np.array([[2,7,-1,3,1],
              [2,3,4,1,7],
              [6,2,-3,2,-1],
              [2,1,2,-1,2],
              [3,4,1,-2,1]],float)
B = np.array([[5],
              [7],
              [2],
              [3],
              [4]],float)
n=len(B)

for k in range(n):
    if np.fabs(A[k,k])<1.0*np.exp(-12):

        for i in range(k+1,n):
            if np.fabs(A[i,k])>np.fabs(A[k,k]):

                for j in range(k,n):
                    A[k,j], A[i,j] = A[i,j], A[k,j]

                B[k],B[i] = B[i], B[k]
                break
    
    #Division of the pivot row
    pivot = A[k,k]
    for j in range (k,n):
        A[k,j]/=pivot
    B[k]/= pivot
    #Elimination loop
    for i in range(n):
        if i ==k or A[i,k]==0:
            continue
        factor = A[i,k]
        for j in range (k,n):
            A[i,j] -= factor *A[k,j]
        B[i] -= factor *B[k]

print(A)
print(B)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.44444444]
 [0.55555556]
 [0.66666667]
 [0.22222222]
 [0.22222222]]


In [9]:
def Gauss_elimination (A, B):
    n=len(B)
    X = np.zeros(n, float)

    #Elimination 
    for k in range(n-1):
        for i in range(k+1, n):
            factr = A[k,k]/A[i,k]
            for j in range (k,n):
                A[i,j]=A[k,j]-factr*A[i,j]
            B[i] = B[k]-factr*B[i]

    #Backward substitution 

    X[n-1] = B[n-1]/A[n-1,n-1]

    for i in range (n-2,-1,-1):
        Sum =0
        for j in range (i+1, n):
            Sum+=A[i,j]*X[j]
        X[i] = (B[i]-Sum)/A[i,i]
    print("The solution using Gauss Elimination: ", X)

def Jacobi_method(A,B):
    (n,) = np.shape(B)
    X_new = np.empty(n, float)
    X = np.full(n,1.0, float)
    max_iter = 100
    tolerance = 1*np.exp(-8)
    for iteration in range (max_iter):

        for i in range (n):
            Sum = 0
            for j in range (n):
                if j!=i:
                    Sum+=A[i,j]*X[j]
            X_new[i] = - (Sum-B[i])/(A[i,i])
        if (np.abs(X_new-X)<tolerance).all():
            break
        else:
            X = np.copy(X_new)
    print ("The solution using Jacobi's Method: ",X)

def Gauss_seidel(A,B):
    (n,) = np.shape(B)
    X_new = np.empty(n, float)
    X = np.full(n,1.0, float)
    max_iter = 100
    tolerance = 1*np.exp(-8)
    for iteration in range (max_iter):

        for i in range (n):
            Sum = 0
            for j in range (n):
                if j!=i:
                    Sum+=A[i,j]*X_new[j]
            X_new[i] = - (Sum-B[i])/(A[i,i])
        if (np.abs(X_new-X)<tolerance).all():
            break
        else:
            X = np.copy(X_new)
    print ("The solution using Gauss Seidel Method: ",X)

def Gauss_Jordan_method(A,B):
    n=len(B)

    for k in range(n):
        if np.fabs(A[k,k])<1.0*np.exp(-12):

            for i in range(k+1,n):
                if np.fabs(A[i,k])>np.fabs(A[k,k]):

                    for j in range(k,n):
                        A[k,j], A[i,j] = A[i,j], A[k,j]

                    B[k],B[i] = B[i], B[k]
                    break
    
        #Division of the pivot row
        pivot = A[k,k]
        for j in range (k,n):
            A[k,j]/=pivot
        B[k]/= pivot
        #Elimination loop
        for i in range(n):
            if i ==k or A[i,k]==0:
                continue
            factor = A[i,k]
            for j in range (k,n):
                A[i,j] -= factor *A[k,j]
            B[i] -= factor *B[k]
    print("The soluting using Gauss Jordan's Method: ", B)

import numpy as np

A = np.array([[4, -1, 1],
              [4, -8, 1],
              [-2, 1, 5]],float)
B = np.array([7,-21,15], float)

Gauss_elimination(A,B)

Sum_values_in_row = np.sum(abs(A), axis=1)
if np.all(((abs(np.diag(A))))>=Sum_values_in_row):
    Gauss_seidel(A,B)
    Jacobi_method(A,B)
else:
    Gauss_Jordan_method(A,B)
Exact_sol = np.linalg.solve(A,B)
print("The exact solution: ",Exact_sol)

The solution using Gauss Elimination:  [2. 4. 3.]
The soluting using Gauss Jordan's Method:  [2. 4. 3.]
The exact solution:  [2. 4. 3.]
